//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTR
    {
        public int DTRId { get; set; }
        public Nullable<int> EnrolleeId { get; set; }
        public Nullable<int> EnrolleeNo { get; set; }
        public Nullable<System.DateTime> DTRDate { get; set; }
        public string DTRDay { get; set; }
        public string TimeInAM { get; set; }
        public string TimeOutAM { get; set; }
        public string TimeInPM { get; set; }
        public string TimeOutPM { get; set; }
        public string TimeInOT { get; set; }
        public string TimeOutOT { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public Nullable<double> TotalMinute { get; set; }
        public Nullable<double> TotalHour { get; set; }
        public string DTRStatus { get; set; }
        public Nullable<bool> IsSource { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        public virtual Enrollee Enrollee { get; set; }
    }
}
