//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int HolidayId { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public Nullable<bool> HolidayActive { get; set; }
        public string HolidayType { get; set; }
        public string HolidayNote { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    }
}
