//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacDumpLog
    {
        public int MacDumpId { get; set; }
        public Nullable<int> EnrolleeId { get; set; }
        public Nullable<int> MachineNo { get; set; }
        public Nullable<int> EnrolleeNo { get; set; }
        public Nullable<int> MachineInsId { get; set; }
        public string MacDumpDate { get; set; }
        public string MacDumpTime { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        public virtual MachineInstance MachineInstance { get; set; }
    }
}
