//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miscellaneou
    {
        public int MiscId { get; set; }
        public Nullable<int> MiscGraceInAM { get; set; }
        public Nullable<int> MiscGraceInPM { get; set; }
        public Nullable<int> MiscGraceInOT { get; set; }
        public Nullable<double> MiscRegularHours { get; set; }
        public string MiscRegularLabel { get; set; }
        public string MiscOverRegularLabel { get; set; }
        public string MiscUnderRegularLabel { get; set; }
        public Nullable<bool> MiscActive { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    }
}
