//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionId { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
