//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Setting()
        {
            this.SettingDetails = new HashSet<SettingDetail>();
        }
    
        public int SettingId { get; set; }
        public string SettingName { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EdtiedOn { get; set; }
    
        public virtual ICollection<SettingDetail> SettingDetails { get; set; }
    }
}
