//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingDetail
    {
        public int SettingDetailId { get; set; }
        public Nullable<int> SettingId { get; set; }
        public string SettingDetailDay { get; set; }
        public Nullable<System.DateTime> SettingDetailAMIn01 { get; set; }
        public Nullable<System.DateTime> SettingDetailAMIn02 { get; set; }
        public Nullable<System.DateTime> SettingDetailAMOut01 { get; set; }
        public Nullable<System.DateTime> SettingDetailAMOut02 { get; set; }
        public Nullable<System.DateTime> SettingDetailPMIn01 { get; set; }
        public Nullable<System.DateTime> SettingDetailPMIn02 { get; set; }
        public Nullable<System.DateTime> SettingDetailPMOut01 { get; set; }
        public Nullable<System.DateTime> SettingDetailPMOut02 { get; set; }
        public Nullable<System.DateTime> SettingDetailOTIn01 { get; set; }
        public Nullable<System.DateTime> SettingDetailOTIn02 { get; set; }
        public Nullable<System.DateTime> SettingDetailOTOut01 { get; set; }
        public Nullable<System.DateTime> SettingDetailOTOut02 { get; set; }
        public Nullable<System.DateTime> SettingDetailINAM { get; set; }
        public Nullable<System.DateTime> SettingDetailOUTAM { get; set; }
        public Nullable<System.DateTime> SettingDetailINPM { get; set; }
        public Nullable<System.DateTime> SettingDetailOUTPM { get; set; }
        public Nullable<System.DateTime> SettingDetailINOT { get; set; }
        public Nullable<System.DateTime> SettingDetailOUTOT { get; set; }
        public Nullable<bool> SettingDetailActive { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        public virtual Setting Setting { get; set; }
    }
}
